#ifndef __ZGOLD_DEBUG_PANEL_MQH__
#define __ZGOLD_DEBUG_PANEL_MQH__
#define ZGOLD_PANEL_PREFIX "ZGOLD_DEBUG_"
#define ZGOLD_PANEL_PENDING_LINES 6
#define ZGOLD_PANEL_LIFECYCLE_LINES 5
#define ZGOLD_PANEL_CANDIDATE_LINES 6
class DebugPanel
{
private:
 long m_tick_count; string m_runtime_state; string m_last_event; string m_error; bool m_core,m_market,m_reconciler,m_trailing,m_state,m_decision_module,m_candidate_module,m_geometry_module;
 string m_operational_state,m_state_reason,m_decision,m_action,m_decision_reason; int m_decision_ticket;
 string m_geometry_status,m_geometry_reason; double m_geometry_candidate,m_geometry_step,m_geometry_twostep;
 int m_buy_count,m_sell_count; double m_buy_lots,m_sell_lots,m_buy_profit,m_sell_profit,m_total_profit;
 int m_pending_count; int m_pending_ticket[ZGOLD_PANEL_PENDING_LINES]; int m_pending_type[ZGOLD_PANEL_PENDING_LINES]; double m_pending_lots[ZGOLD_PANEL_PENDING_LINES]; double m_pending_price[ZGOLD_PANEL_PENDING_LINES];
 string m_transition; int m_life_ticket,m_life_prev_type,m_life_cur_type; double m_life_prev_lots,m_life_cur_lots,m_life_prev_price,m_life_cur_price;
 string m_life_history[ZGOLD_PANEL_LIFECYCLE_LINES]; int m_life_history_count;
 int m_trail_count; int m_trail_ticket[ZGOLD_PANEL_PENDING_LINES]; int m_trail_type[ZGOLD_PANEL_PENDING_LINES]; double m_trail_delta[ZGOLD_PANEL_PENDING_LINES]; string m_trail_class[ZGOLD_PANEL_PENDING_LINES]; bool m_trail_valid[ZGOLD_PANEL_PENDING_LINES];
 int m_candidate_count; int m_candidate_ticket[ZGOLD_PANEL_CANDIDATE_LINES]; double m_candidate_price[ZGOLD_PANEL_CANDIDATE_LINES]; bool m_candidate_valid[ZGOLD_PANEL_CANDIDATE_LINES]; string m_candidate_reason[ZGOLD_PANEL_CANDIDATE_LINES];
 void Label(string id,int x,int y,string text,int size=9){string n=ZGOLD_PANEL_PREFIX+id;if(ObjectFind(0,n)<0){ObjectCreate(0,n,OBJ_LABEL,0,0,0);ObjectSetInteger(0,n,OBJPROP_CORNER,CORNER_LEFT_UPPER);ObjectSetInteger(0,n,OBJPROP_XDISTANCE,x);ObjectSetInteger(0,n,OBJPROP_YDISTANCE,y);ObjectSetInteger(0,n,OBJPROP_FONTSIZE,size);ObjectSetString(0,n,OBJPROP_FONT,"Consolas");ObjectSetInteger(0,n,OBJPROP_COLOR,clrWhite);ObjectSetInteger(0,n,OBJPROP_SELECTABLE,false);}ObjectSetString(0,n,OBJPROP_TEXT,text);}
 void Background(){string n=ZGOLD_PANEL_PREFIX+"BACKGROUND";if(ObjectFind(0,n)<0){ObjectCreate(0,n,OBJ_RECTANGLE_LABEL,0,0,0);ObjectSetInteger(0,n,OBJPROP_CORNER,CORNER_LEFT_UPPER);ObjectSetInteger(0,n,OBJPROP_XDISTANCE,10);ObjectSetInteger(0,n,OBJPROP_YDISTANCE,10);ObjectSetInteger(0,n,OBJPROP_XSIZE,620);ObjectSetInteger(0,n,OBJPROP_YSIZE,570);ObjectSetInteger(0,n,OBJPROP_BGCOLOR,clrBlack);ObjectSetInteger(0,n,OBJPROP_BORDER_COLOR,clrDimGray);ObjectSetInteger(0,n,OBJPROP_SELECTABLE,false);}}
 string TypeName(int t){if(t==OP_BUY)return "BUY";if(t==OP_SELL)return "SELL";if(t==OP_BUYSTOP)return "BUY STOP";if(t==OP_SELLSTOP)return "SELL STOP";if(t==OP_BUYLIMIT)return "BUY LIMIT";if(t==OP_SELLLIMIT)return "SELL LIMIT";return "-";}
 void PushLifecycle(string text){if(text==""||text=="NO CHANGE")return;for(int i=ZGOLD_PANEL_LIFECYCLE_LINES-1;i>0;i--)m_life_history[i]=m_life_history[i-1];m_life_history[0]=text;if(m_life_history_count<ZGOLD_PANEL_LIFECYCLE_LINES)m_life_history_count++;}
public:
 DebugPanel(){m_tick_count=0;m_runtime_state="RESET";m_last_event="WAITING";m_error="";m_core=false;m_market=false;m_reconciler=false;m_trailing=false;m_state=false;m_decision_module=false;m_candidate_module=false;m_geometry_module=false;m_operational_state="RESET";m_state_reason="NO STATE";m_decision="NOT IMPLEMENTED";m_action="NONE";m_decision_reason="NOT EVALUATED";m_decision_ticket=-1;m_geometry_status="UNRESOLVED";m_geometry_reason="NOT EVALUATED";m_geometry_candidate=0;m_geometry_step=.80;m_geometry_twostep=.90;m_buy_count=0;m_sell_count=0;m_buy_lots=0;m_sell_lots=0;m_buy_profit=0;m_sell_profit=0;m_total_profit=0;m_pending_count=0;m_transition="NO CHANGE";m_life_ticket=-1;m_life_prev_type=-1;m_life_cur_type=-1;m_life_prev_lots=0;m_life_cur_lots=0;m_life_prev_price=0;m_life_cur_price=0;m_life_history_count=0;m_trail_count=0;m_candidate_count=0;for(int i=0;i<ZGOLD_PANEL_PENDING_LINES;i++){m_pending_ticket[i]=-1;m_pending_type[i]=0;m_pending_lots[i]=0;m_pending_price[i]=0;m_trail_ticket[i]=-1;m_trail_type[i]=-1;m_trail_delta[i]=0;m_trail_class[i]="UNRESOLVED";m_trail_valid[i]=false;}for(int j=0;j<ZGOLD_PANEL_LIFECYCLE_LINES;j++)m_life_history[j]="";for(int k=0;k<ZGOLD_PANEL_CANDIDATE_LINES;k++){m_candidate_ticket[k]=-1;m_candidate_price[k]=0;m_candidate_valid[k]=false;m_candidate_reason[k]="-";}}
 void Initialize(){Background();Render();} void IncrementTick(){m_tick_count++;}
 void SetModuleStatus(string m,bool s){if(m=="CORE")m_core=s;else if(m=="MARKET STATE")m_market=s;else if(m=="STATE RECONCILER")m_reconciler=s;else if(m=="PENDING TRAILING")m_trailing=s;else if(m=="OPERATIONAL STATE")m_state=s;else if(m=="DECISION OBSERVER")m_decision_module=s;else if(m=="CANDIDATE OBSERVER")m_candidate_module=s;else if(m=="GEOMETRY OBSERVER")m_geometry_module=s;} void SetRuntimeState(string s){m_runtime_state=s;} void SetLastEvent(string s){m_last_event=s;} void SetError(string s){m_error=s;}
 void SetOperationalState(string state,string reason){m_operational_state=state;m_state_reason=reason;} void SetDecisionAction(string decision,string action,string reason,int ticket){m_decision=decision;m_action=action;m_decision_reason=reason;m_decision_ticket=ticket;} void SetGeometry(string status,string reason,double candidate,double step,double twostep){m_geometry_status=status;m_geometry_reason=reason;m_geometry_candidate=candidate;m_geometry_step=step;m_geometry_twostep=twostep;}
 void SetMarket(double b,double a,double sp,datetime t){Label("BID",25,120,"Bid       : "+DoubleToString(b,Digits));Label("ASK",25,135,"Ask       : "+DoubleToString(a,Digits));Label("SPREAD",25,150,"Spread    : "+DoubleToString(sp,1)+" points");Label("TIME",25,165,"Server    : "+TimeToString(t,TIME_DATE|TIME_SECONDS));}
 void SetExposure(int bc,double bl,double bp,int sc,double sl,double sp,double tp){m_buy_count=bc;m_buy_lots=bl;m_buy_profit=bp;m_sell_count=sc;m_sell_lots=sl;m_sell_profit=sp;m_total_profit=tp;}
 void SetPending(PendingState &p){m_pending_count=p.Count();for(int i=0;i<ZGOLD_PANEL_PENDING_LINES;i++){m_pending_ticket[i]=-1;m_pending_type[i]=0;m_pending_lots[i]=0;m_pending_price[i]=0;if(i<m_pending_count){m_pending_ticket[i]=p.Ticket(i);m_pending_type[i]=p.Type(i);m_pending_lots[i]=p.Lots(i);m_pending_price[i]=p.Price(i);}}}
 void SetLifecycle(int ev,int ticket,int prev_type,int cur_type,double prev_lots,double cur_lots,double prev_price,double cur_price,string text){m_transition=text;m_life_ticket=ticket;m_life_prev_type=prev_type;m_life_cur_type=cur_type;m_life_prev_lots=prev_lots;m_life_cur_lots=cur_lots;m_life_prev_price=prev_price;m_life_cur_price=cur_price;if(text!="NO CHANGE"&&text!="INITIAL SNAPSHOT")PushLifecycle(text);}
 void SetTrailingInventory(int count,int &tickets[],int &types[],double &deltas[],string &classes[],bool &valids[]){m_trail_count=count;if(m_trail_count>ZGOLD_PANEL_PENDING_LINES)m_trail_count=ZGOLD_PANEL_PENDING_LINES;for(int i=0;i<ZGOLD_PANEL_PENDING_LINES;i++){m_trail_ticket[i]=-1;m_trail_type[i]=-1;m_trail_delta[i]=0;m_trail_class[i]="-";m_trail_valid[i]=false;if(i<m_trail_count){m_trail_ticket[i]=tickets[i];m_trail_type[i]=types[i];m_trail_delta[i]=deltas[i];m_trail_class[i]=classes[i];m_trail_valid[i]=valids[i];}}}
 void SetCandidateInventory(int count,int &tickets[],double &prices[],bool &valids[],string &reasons[]){m_candidate_count=count;if(m_candidate_count>ZGOLD_PANEL_CANDIDATE_LINES)m_candidate_count=ZGOLD_PANEL_CANDIDATE_LINES;for(int i=0;i<ZGOLD_PANEL_CANDIDATE_LINES;i++){m_candidate_ticket[i]=-1;m_candidate_price[i]=0;m_candidate_valid[i]=false;m_candidate_reason[i]="-";if(i<m_candidate_count){m_candidate_ticket[i]=tickets[i];m_candidate_price[i]=prices[i];m_candidate_valid[i]=valids[i];m_candidate_reason[i]=reasons[i];}}}
 void Render(){Background();int x=25;Label("TITLE",x,18,"ZGOLD - DEBUG PANEL",11);Label("SYSTEM",x,45,"SYSTEM",9);Label("STATUS",x,60,"EA        : "+m_runtime_state);Label("SYMBOL",x,75,"SYMBOL    : "+Symbol());Label("MARKET",x,105,"MARKET",9);Label("RUNTIME",x,190,"RUNTIME",9);Label("TICK",x,205,"Tick      : "+IntegerToString((int)m_tick_count));Label("EXPOSURE",x,230,"EXPOSURE",9);Label("BUY",x,245,"BUY       : "+IntegerToString(m_buy_count)+" | "+DoubleToString(m_buy_lots,2)+" | "+DoubleToString(m_buy_profit,2));Label("SELL",x,260,"SELL      : "+IntegerToString(m_sell_count)+" | "+DoubleToString(m_sell_lots,2)+" | "+DoubleToString(m_sell_profit,2));Label("TOTAL",x,275,"TOTAL P/L : "+DoubleToString(m_total_profit,2));Label("PENDING",x,300,"PENDING : "+IntegerToString(m_pending_count),9);for(int i=0;i<ZGOLD_PANEL_PENDING_LINES;i++){string id="P"+IntegerToString(i);string tx="";if(i<m_pending_count)tx=TypeName(m_pending_type[i])+" #"+IntegerToString(m_pending_ticket[i])+" | "+DoubleToString(m_pending_lots[i],2)+" | "+DoubleToString(m_pending_price[i],Digits);Label(id,x,315+i*15,tx);}
 Label("MODULES",330,45,"MODULES",9);Label("CORE",330,60,"Core            ["+(m_core?"OK":"WAIT")+"]");Label("MARKET_MODULE",330,75,"MarketState     ["+(m_market?"OK":"WAIT")+"]");Label("RECONCILER",330,90,"Reconciler      ["+(m_reconciler?"OK":"WAIT")+"]");Label("TRAIL_MODULE",330,105,"PendingTrailing ["+(m_trailing?"OK":"WAIT")+"]");Label("STATE_MODULE",330,120,"OperationalState ["+(m_state?"OK":"WAIT")+"]");Label("DEC_MODULE",330,135,"DecisionObserver ["+(m_decision_module?"OK":"WAIT")+"]");Label("CAND_MODULE",330,150,"CandidateObserver["+(m_candidate_module?"OK":"WAIT")+"]");Label("GEO_MODULE",330,165,"GeometryObserver ["+(m_geometry_module?"OK":"WAIT")+"]");Label("STATE",330,185,"STATE      : "+m_operational_state);Label("STATE_REASON",330,200,"Reason     : "+m_state_reason);Label("DECISION",330,215,"DECISION   : "+m_decision+" #"+IntegerToString(m_decision_ticket));Label("ACTION",330,230,"ACTION     : "+m_action);Label("DEC_REASON",330,245,"Reason     : "+m_decision_reason);Label("GEOMETRY",330,265,"GEOMETRY OBSERVER",9);Label("GEO_STATUS",330,280,"Status     : "+m_geometry_status);Label("GEO_CAND",330,295,"Candidate  : "+DoubleToString(m_geometry_candidate,Digits));Label("GEO_STEP",330,310,"Step       : "+DoubleToString(m_geometry_step,2));Label("GEO_TWOSTEP",330,325,"TwoStep    : "+DoubleToString(m_geometry_twostep,2));Label("GEO_REASON",330,340,"Reason     : "+m_geometry_reason);Label("EVENT",330,360,"LAST EVENT",9);Label("LAST_EVENT",330,375,"> "+m_last_event);Label("LIFECYCLE",330,400,"LIFECYCLE TRACE",9);Label("LIFE_TRANS",330,415,"Last       : "+m_transition);Label("LIFE_TICKET",330,430,"Ticket     : #"+IntegerToString(m_life_ticket));Label("LIFE_PREV",330,445,"Previous   : "+TypeName(m_life_prev_type)+" | "+DoubleToString(m_life_prev_lots,2)+" | "+DoubleToString(m_life_prev_price,Digits));Label("LIFE_CUR",330,460,"Current    : "+TypeName(m_life_cur_type)+" | "+DoubleToString(m_life_cur_lots,2)+" | "+DoubleToString(m_life_cur_price,Digits));for(int h=0;h<ZGOLD_PANEL_LIFECYCLE_LINES;h++)Label("LH"+IntegerToString(h),330,475+h*12,(h<m_life_history_count?"  "+m_life_history[h]:""),8);Label("TRAIL",330,535,"TRAILING ["+IntegerToString(m_trail_count)+"]",9);for(int j=0;j<ZGOLD_PANEL_PENDING_LINES;j++){string tid="TRAIL_"+IntegerToString(j);string tt="";if(j<m_trail_count)tt="#"+IntegerToString(m_trail_ticket[j])+" "+TypeName(m_trail_type[j])+" | d="+DoubleToString(m_trail_delta[j],2)+" | "+m_trail_class[j]+" | "+(m_trail_valid[j]?"OK":"NO");Label(tid,330,550+j*14,tt);}Label("CANDIDATE",25,420,"CANDIDATE",9);for(int c=0;c<ZGOLD_PANEL_CANDIDATE_LINES;c++){string cid="C"+IntegerToString(c);string ct="";if(c<m_candidate_count)ct="#"+IntegerToString(m_candidate_ticket[c])+" | "+DoubleToString(m_candidate_price[c],Digits)+" | "+(m_candidate_valid[c]?"VALID":"NO")+" | "+m_candidate_reason[c];Label(cid,25,435+c*14,ct);}if(m_error!="")Label("ERROR",330,645,"> ERROR: "+m_error);}
 void Destroy(){for(int i=ObjectsTotal()-1;i>=0;i--){string n=ObjectName(i);if(StringFind(n,ZGOLD_PANEL_PREFIX,0)==0)ObjectDelete(0,n);}}
};
#endif
