#ifndef __ZGOLD_DEBUG_PANEL_MQH__
#define __ZGOLD_DEBUG_PANEL_MQH__
#define ZGOLD_PANEL_PREFIX "ZGOLD_DEBUG_"
#define ZGOLD_PANEL_PENDING_LINES 6
class DebugPanel
{
private:
 long m_tick_count; string m_runtime_state; string m_last_event; string m_error; bool m_core,m_market,m_reconciler;
 int m_buy_count,m_sell_count; double m_buy_lots,m_sell_lots,m_buy_profit,m_sell_profit,m_total_profit;
 int m_pending_count; int m_pending_ticket[ZGOLD_PANEL_PENDING_LINES]; int m_pending_type[ZGOLD_PANEL_PENDING_LINES]; double m_pending_lots[ZGOLD_PANEL_PENDING_LINES]; double m_pending_price[ZGOLD_PANEL_PENDING_LINES];
 string m_transition; int m_life_ticket,m_life_prev_type,m_life_cur_type; double m_life_prev_lots,m_life_cur_lots,m_life_prev_price,m_life_cur_price;
 void Label(string id,int x,int y,string text,int size=9){string n=ZGOLD_PANEL_PREFIX+id;if(ObjectFind(0,n)<0){ObjectCreate(0,n,OBJ_LABEL,0,0,0);ObjectSetInteger(0,n,OBJPROP_CORNER,CORNER_LEFT_UPPER);ObjectSetInteger(0,n,OBJPROP_XDISTANCE,x);ObjectSetInteger(0,n,OBJPROP_YDISTANCE,y);ObjectSetInteger(0,n,OBJPROP_FONTSIZE,size);ObjectSetString(0,n,OBJPROP_FONT,"Consolas");ObjectSetInteger(0,n,OBJPROP_COLOR,clrWhite);ObjectSetInteger(0,n,OBJPROP_SELECTABLE,false);}ObjectSetString(0,n,OBJPROP_TEXT,text);}
 void Background(){string n=ZGOLD_PANEL_PREFIX+"BACKGROUND";if(ObjectFind(0,n)<0){ObjectCreate(0,n,OBJ_RECTANGLE_LABEL,0,0,0);ObjectSetInteger(0,n,OBJPROP_CORNER,CORNER_LEFT_UPPER);ObjectSetInteger(0,n,OBJPROP_XDISTANCE,10);ObjectSetInteger(0,n,OBJPROP_YDISTANCE,10);ObjectSetInteger(0,n,OBJPROP_XSIZE,560);ObjectSetInteger(0,n,OBJPROP_YSIZE,560);ObjectSetInteger(0,n,OBJPROP_BGCOLOR,clrBlack);ObjectSetInteger(0,n,OBJPROP_BORDER_COLOR,clrDimGray);ObjectSetInteger(0,n,OBJPROP_SELECTABLE,false);}}
 string TypeName(int t){if(t==OP_BUY)return "BUY";if(t==OP_SELL)return "SELL";if(t==OP_BUYSTOP)return "BUY STOP";if(t==OP_SELLSTOP)return "SELL STOP";if(t==OP_BUYLIMIT)return "BUY LIMIT";if(t==OP_SELLLIMIT)return "SELL LIMIT";return "-";}
public:
 DebugPanel(){m_tick_count=0;m_runtime_state="RESET";m_last_event="WAITING";m_error="";m_core=false;m_market=false;m_reconciler=false;m_buy_count=0;m_sell_count=0;m_buy_lots=0;m_sell_lots=0;m_buy_profit=0;m_sell_profit=0;m_total_profit=0;m_pending_count=0;m_transition="NO CHANGE";m_life_ticket=-1;m_life_prev_type=-1;m_life_cur_type=-1;m_life_prev_lots=0;m_life_cur_lots=0;m_life_prev_price=0;m_life_cur_price=0;for(int i=0;i<ZGOLD_PANEL_PENDING_LINES;i++){m_pending_ticket[i]=-1;m_pending_type[i]=0;m_pending_lots[i]=0;m_pending_price[i]=0;}}
 void Initialize(){Background();Render();} void IncrementTick(){m_tick_count++;}
 void SetModuleStatus(string m,bool s){if(m=="CORE")m_core=s;else if(m=="MARKET STATE")m_market=s;else if(m=="STATE RECONCILER")m_reconciler=s;} void SetRuntimeState(string s){m_runtime_state=s;} void SetLastEvent(string s){m_last_event=s;} void SetError(string s){m_error=s;}
 void SetMarket(double b,double a,double sp,datetime t){Label("BID",25,110,"Bid       : "+DoubleToString(b,Digits));Label("ASK",25,130,"Ask       : "+DoubleToString(a,Digits));Label("SPREAD",25,150,"Spread    : "+DoubleToString(sp,1)+" points");Label("TIME",25,170,"Server    : "+TimeToString(t,TIME_DATE|TIME_SECONDS));}
 void SetExposure(int bc,double bl,double bp,int sc,double sl,double sp,double tp){m_buy_count=bc;m_buy_lots=bl;m_buy_profit=bp;m_sell_count=sc;m_sell_lots=sl;m_sell_profit=sp;m_total_profit=tp;}
 void SetPending(PendingState &p){m_pending_count=p.Count();for(int i=0;i<ZGOLD_PANEL_PENDING_LINES;i++){m_pending_ticket[i]=-1;m_pending_type[i]=0;m_pending_lots[i]=0;m_pending_price[i]=0;if(i<m_pending_count){m_pending_ticket[i]=p.Ticket(i);m_pending_type[i]=p.Type(i);m_pending_lots[i]=p.Lots(i);m_pending_price[i]=p.Price(i);}}}
 void SetLifecycle(int ev,int ticket,int prev_type,int cur_type,double prev_lots,double cur_lots,double prev_price,double cur_price,string text){m_transition=text;m_life_ticket=ticket;m_life_prev_type=prev_type;m_life_cur_type=cur_type;m_life_prev_lots=prev_lots;m_life_cur_lots=cur_lots;m_life_prev_price=prev_price;m_life_cur_price=cur_price;}
 void Render(){Background();int x=25;Label("TITLE",x,20,"ZGOLD - DEBUG PANEL",11);Label("SYSTEM",x,55,"SYSTEM",9);Label("STATUS",x,75,"EA        : "+m_runtime_state);Label("SYMBOL",x,95,"SYMBOL    : "+Symbol());Label("MARKET",x,195,"MARKET",9);Label("RUNTIME",x,235,"RUNTIME",9);Label("TICK",x,255,"Tick      : "+IntegerToString((int)m_tick_count));Label("EXPOSURE",x,290,"EXPOSURE",9);Label("BUY",x,310,"BUY       : "+IntegerToString(m_buy_count)+" | "+DoubleToString(m_buy_lots,2)+" | "+DoubleToString(m_buy_profit,2));Label("SELL",x,330,"SELL      : "+IntegerToString(m_sell_count)+" | "+DoubleToString(m_sell_lots,2)+" | "+DoubleToString(m_sell_profit,2));Label("TOTAL",x,350,"TOTAL P/L : "+DoubleToString(m_total_profit,2));Label("PENDING",x,385,"PENDING : "+IntegerToString(m_pending_count),9);for(int i=0;i<ZGOLD_PANEL_PENDING_LINES;i++){string id="P"+IntegerToString(i);string tx="";if(i<m_pending_count)tx=TypeName(m_pending_type[i])+" #"+IntegerToString(m_pending_ticket[i])+" | "+DoubleToString(m_pending_lots[i],2)+" | "+DoubleToString(m_pending_price[i],Digits);Label(id,x,405+i*20,tx);}
 Label("MODULES",310,55,"MODULES",9);Label("CORE",310,75,"Core            ["+(m_core?"OK":"WAIT")+"]");Label("MARKET_MODULE",310,95,"MarketState     ["+(m_market?"OK":"WAIT")+"]");Label("RECONCILER",310,115,"Reconciler      ["+(m_reconciler?"OK":"WAIT")+"]");Label("EVENT",310,195,"LAST EVENT",9);Label("LAST_EVENT",310,215,"> "+m_last_event);Label("LIFECYCLE",310,270,"LIFECYCLE TRACE",9);Label("LIFE_TRANS",310,290,"Transition : "+m_transition);Label("LIFE_TICKET",310,310,"Ticket     : #"+IntegerToString(m_life_ticket));Label("LIFE_PREV",310,330,"Previous   : "+TypeName(m_life_prev_type)+" | "+DoubleToString(m_life_prev_lots,2)+" | "+DoubleToString(m_life_prev_price,Digits));Label("LIFE_CUR",310,350,"Current    : "+TypeName(m_life_cur_type)+" | "+DoubleToString(m_life_cur_lots,2)+" | "+DoubleToString(m_life_cur_price,Digits));if(m_error!="")Label("ERROR",310,390,"> ERROR: "+m_error);}
 void Destroy(){for(int i=ObjectsTotal()-1;i>=0;i--){string n=ObjectName(i);if(StringFind(n,ZGOLD_PANEL_PREFIX,0)==0)ObjectDelete(0,n);}}
};
#endif
